// 객체 저장하는 js
// 1 -> 빵 100 -> 케이크 200 -> 델리 300 -> 음료
menus = {
  breads: {
    bread1: {
      best: true,
      type: 1,
      sub_type: "파이",
      url: "images/menuImg/menu-img00.png",
      name: "사르르 리본파이",
      en_name: "Sarur Ribbon Pie",
      info: "결결이 버터 풍미 가득, 달콤한 카라멜 토핑을 더해 입 안에서 사르르 녹는 리본 모양 파이",
      kcal: 500,
      saturatedFat: 20,
      sugar: 11,
      sodium: 280,
      protein: 6,
      caffeine: 0,
      allergy: "계란, 우유, 밀",
      gram: 95,
    },
    bread2: {
      best: false,
      type: 2,
      sub_type: "식빵",
      url: "images/menuImg/menu-img01.png",
      name: "2배 더 진해진 순진우유 식빵",
      en_name: "Pure Milk Bread Twice as Rich",
      info: "2배 더 진해진 우유 함량과 순우유 탕종으로 보들보들한 빵결 속에 진한 우유의 고소한 풍미를 가득 담은 우유 식빵",
      kcal: 1285,
      saturatedFat: 15,
      sugar: 41,
      sodium: 1910,
      protein: 37,
      caffeine: 0,
      allergy: "우유, 밀",
      gram: 439,
    },
    bread3: {
      best: false,
      type: 3,
      sub_type: "파이",
      url: "images/menuImg/menu-img02.png",
      name: "카라멜피칸 소보로프",
      en_name: "Caramel Pecan Soboroff",
      info: "돌돌 말려있는 로프 모양의 바삭한 패스트리에 달콤한 카라멜과 고소한 피칸과 호두, 쿠키소보로를 더한 간식형 패스트리",
      kcal: 815,
      saturatedFat: 22,
      sugar: 40,
      sodium: 620,
      protein: 11,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류, 호두",
      gram: 160,
    },
    bread4: {
      best: false,
      type: 4,
      sub_type: "건강빵",
      url: "images/menuImg/menu-img03.png",
      name: "프랑스 바게트",
      en_name: "French Baguette",
      info: "프랑스산 밀가루가 들어가 겉은 더 바삭하고 속은 더 촉촉한, 구수한 맛의 정통 바게트",
      kcal: 685,
      saturatedFat: 0.7,
      sugar: 3,
      sodium: 1400,
      protein: 27,
      caffeine: 0,
      allergy: "밀",
      gram: 250,
    },
    bread5: {
      best: false,
      type: 5,
      sub_type: "간식빵",
      url: "images/menuImg/menu-img04.png",
      name: "바삭 마늘빵",
      en_name: "Crispy Garlic Bread",
      info: "마늘의 향긋함과 버터의 고소한 맛을 그대로 담은 바삭한 식감의 마늘 바게트",
      kcal: 205,
      saturatedFat: 8,
      sugar: 5,
      sodium: 220,
      protein: 4,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀",
      gram: 42,
    },
    bread6: {
      best: false,
      type: 6,
      sub_type: "건강빵",
      url: "images/menuImg/menu-img05.png",
      name: "데일리 베이글",
      en_name: "Daily Bagel",
      info: "폭신하고 쫄깃한 기지에 담백한 플레인 베이글",
      kcal: 310,
      saturatedFat: 1.5,
      sugar: 12,
      sodium: 460,
      protein: 12,
      caffeine: 0,
      allergy: "밀, 우유",
      gram: 110,
    },
    bread7: {
      best: false,
      type: 7,
      sub_type: "건강빵",
      url: "images/menuImg/menu-img06.png",
      name: "베리베리 건강브레드",
      en_name: "Very Berry Health Bread",
      info: "유럽빵 고유의 담백함과 원재료 본연의 새콤, 달콤한 맛을 동시에 즐길 수 있는 유럽 건강 브레드",
      kcal: 280,
      saturatedFat: 0.6,
      sugar: 11,
      sodium: 400,
      protein: 7,
      caffeine: 0,
      allergy: "밀, 우유",
      gram: 95,
    },
    bread8: {
      best: false,
      type: 8,
      sub_type: "간식빵",
      url: "images/menuImg/menu-img07.png",
      name: "단팥빵",
      en_name: "Sweet Red Bean Bread",
      info: "달콤하고 부드러운 단팥 앙금을 듬뿍 넣어 남녀노소 좋아하는 간식빵",
      kcal: 270,
      saturatedFat: 2.5,
      sugar: 17,
      sodium: 230,
      protein: 8,
      caffeine: 0,
      allergy: "밀, 우유, 계란, 대두",
      gram: 86,
    },
    bread9: {
      best: false,
      type: 9,
      url: "images/menuImg/menu-img08.png",
      name: "더 쫄깃해진 그때 그 도나쓰",
      en_name: "Chewier Nostalgic Donut",
      info: "국내산 쌀로 만든 쌀 탕종으로 더 부드럽고 쫄깃해진, 어릴 적 먹던 한입 쏙 미니 찹쌀 도나쓰",
      kcal: 385,
      saturatedFat: 3.3,
      sugar: 21,
      sodium: 710,
      protein: 6,
      caffeine: 0,
      allergy: "대두,밀",
      gram: 131,
    },
    bread10: {
      best: false,
      type: 10,
      sub_type: "식빵",
      url: "images/menuImg/menu-img09.png",
      name: "고메 버터 식빵",
      en_name: "Gome Butter Bread",
      info: "브라운버터를 넣어 버터의 풍미를 올린 촉촉하고 부드러운 빵에 바삭하고 고소한 풍미의 패스트리가 만나 껍질까지 맛있게 먹을 수 있는 맛있는 식빵",
      kcal: 1060,
      sugar: 26,
      protein: 27,
      saturatedFat: 28,
      sodium: 1240,
      caffeine: 0,
      allergy: "계란, 우유, 밀, 아황산류 함유",
      gram: 291
    },
    bread11: {
      best: false,
      type: 11,
      sub_type: "식빵",
      url: "images/menuImg/menu-img10.png",
      name: "호박 패스트리 식빵",
      en_name: "Pumpkin Pastry Bread",
      info: "호박의 고소한 맛을 살린 바삭한 패스트리식빵",
      kcal: 1235,
      sugar: 40,
      protein: 31,
      saturatedFat: 36,
      sodium: 1890,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류",
      gram: 358
    },
  },
  cakes: {
    cake1: {
      best: true,
      type: 100,
      sub_type: "생크림케이크",
      url: "images/menuImg/menu-cake01.png",
      name: "스트로베리 퀸",
      en_name: "Strawberry Queen",
      info: "반짝이는 비즈로 감싼 부드러운 화이트시트에 상큼달콤한 딸기 꿀리를 샌드하고 신선한 생딸기를 가득 올린 생크림 맛집! 뚜레쥬르의 시그니처 케이크",
      kcal: 1765,
      saturatedFat: 57,
      sugar: 131,
      sodium: 710,
      protein: 29,
      caffeine: 0,
      allergy: "계란,우유,대두,밀,돼지고기,아황산류",
      gram: 815,
    },
    cake2: {
      best: false,
      type: 101,
      sub_type: "캐릭터케이크",
      url: "images/menuImg/menu-cake02.png",
      name: "하츄핑의 스타 플래닛",
      en_name: "Hachuping's Star Planet",
      info: "초코&딸기 두 가지 맛을 즐길 수 있는 제품으로 하츄핑 AI 영상편지를 만들 수 있는 쿠폰이 동봉된 케이크",
      kcal: 2965,
      saturatedFat: 90,
      sugar: 197,
      sodium: 1270,
      protein: 28,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류",
      gram: 800
    },
    cake3: {
      best: false,
      type: 102,
      sub_type: "생크림케이크",
      url: "images/menuImg/menu-cake03.png",
      name: "부드러운 초코 쉬폰 2호",
      en_name: "Soft Chocolate Chiffon No.2",
      info: "달콤한 초코 가나슈와 초코 크림이 촉촉하고 폭신한 쉬폰을 만나 더욱 맛있어진 초코 쉬폰 케이크",
      kcal: 2245,
      saturatedFat: 78,
      sugar: 151,
      sodium: 1000,
      protein: 30,
      caffeine: 0,
      allergy: "계란,우유,대두,밀,돼지고기 함유",
      gram: 683
    },
    cake4: {
      best: true,
      type: 103,
      sub_type: "생크림케이크",
      url: "images/menuImg/menu-cake04.png",
      name: "스트로베리 요거트 생크림 케이크",
      en_name: "Strawberry Yogurt Fresh Cream Cake",
      info: "달콤한 생과일과 상큼한 요거트 크림이 한입 가득 기분 좋게 퍼지는 생크림 케이크",
      kcal: 1550,
      saturatedFat: 66,
      sugar: 127,
      sodium: 640,
      protein: 19,
      caffeine: 0,
      allergy: "계란,우유,대두,밀,돼지고기,아황산류",
      gram: 627,
    },
    cake5: {
      best: false,
      type: 104,
      sub_type: "생크림케이크",
      url: "images/menuImg/menu-cake05.png",
      name: "말차에 퐁당 딸기케이크",
      en_name: "Matcha Strawberry Cake",
      info: "산뜻하고 달콤한 딸기 크림에 봄의 싱그러움을 듬뿍 머금은 말차 크림을 더한 그린 & 핑크빛의 사랑스러운 케이크",
      kcal: 1655,
      saturatedFat: 33,
      sugar: 115,
      sodium: 670,
      protein: 24,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 돼지고기, 아황산류",
      gram: 651,
    },
    cake6: {
      best: false,
      type: 105,
      sub_type: "캐릭터케이크",
      url: "images/menuImg/menu-cake06.png",
      name: "짜잔! 잔망루피 꽃다발",
      en_name: "Ta-da! Janmang Loopy Bouquet",
      info: "진한 초코 크림과 다크 초코 가나슈 크림을 샌드한 잔망루피가 짜잔!하고 꽃다발을 든 초코 케이크",
      kcal: 2300,
      saturatedFat: 81,
      sugar: 140,
      sodium: 910,
      protein: 24,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류",
      gram: 580,
    },
    cake7: {
      best: false,
      type: 106,
      url: "images/menuImg/menu-cake07.png",
      sub_type: "캐릭터케이크",
      name: "초롱핑의 초코 유니버스",
      en_name: "Chorongping's Chocolate Universe",
      info: "촉촉한 초코 시트에 달콤한 딸기 크림과 초코 크림이 조화로운 제품으로 우주에서 별똥별을 바라보는 초롱핑의 모습을 담은 케이크",
      kcal: 1550,
      saturatedFat: 60,
      sugar: 93,
      sodium: 330,
      protein: 14,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류",
      gram: 400,
    },
    cake8: {
      best: false,
      type: 107,
      sub_type: "캐릭터케이크",
      url: "images/menuImg/menu-cake08.png",
      name: "헬로카봇 스타가디언",
      en_name: "Hello Carbot Star Guardian",
      info: "변신 헬로카봇! 빅토리 검으로 더욱 강력해진 스타가디언과 함께 즐기는 달콤한 초코 케이크",
      kcal: 2760,
      saturatedFat: 82,
      sugar: 193,
      sodium: 1240,
      protein: 43,
      caffeine: 0,
      allergy: "계란,우유,대두,밀",
      gram: 690,
    },
    cake9: {
      best: false,
      type: 108,
      sub_type: "대형케이크",
      url: "images/menuImg/menu-cake09.png",
      name: "5호 2단 초콜릿케이크",
      en_name: "No. 5 2-tier chocolate cake",
      info: "무언가 특별한 날에 함께 축하하고 싶을 때 좋은 초콜릿 케이크",
      kcal: 9030,
      sugar: 291,
      protein: 183,
      saturatedFat: 224,
      sodium: 2350,
      caffeine: 0,
      allergy: "계란, 밀, 우유, 대두, 돼지고기 함유",
      gram: 1930
    },
    cake10: {
      best: false,
      type: 109,
      sub_type: "무스케이크",
      url: "images/menuImg/menu-cake10.png",
      name: "고구마 케이크 1호",
      en_name: "Sweet Potato Cake No. 1",
      info: "진한 고구마맛을 더하여 한층 풍미가 깊어진 부드러운 고구마케이크",
      kcal: 1255,
      sugar: 77,
      protein: 18,
      saturatedFat: 39,
      sodium: 400,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 돼지고기 함유",
      gram: 465
    },
    cake11: {
      best: false,
      type: 110,
      sub_type: "스페셜케이크",
      url: "images/menuImg/menu-cake11.png",
      name: "쇼콜라 갸또",
      en_name: "Chocolat Gateau",
      info: "초코&블랙초코 시트에 진한 가나슈 초콜릿을 샌드하고 가나슈 초콜릿으로 코팅한 초코케이크",
      kcal: 2430,
      sugar: 148,
      protein: 29,
      saturatedFat: 82,
      sodium: 930,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 돼지고기, 아황산류",
      gram: 710
    },
    cake12: {
      best: false,
      type: 111,
      sub_type: "파티용품",
      url: "images/menuImg/menu-cake12.png",
      name: "해피파티타임 스프링 폭죽",
      en_name: "Happy Party Time Spring Firecrackers",
      info: "축하하는 자리를 컬러풀한 꽃가루로 더욱 아름답게! 화약을 사용하지 않아 누구나 안전하게 사용 가능한 폭죽",
      kcal: 0,
      sugar: 0,
      protein: 0,
      saturatedFat: 0,
      sodium: 0,
      caffeine: 0,
      allergy: "",
      gram: 0
    }
  },
  deli: {
    deli1: {
      best: false,
      type: 200,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del01.png",
      name: "햄치즈 에그 샌드위치",
      en_name: "Ham Cheese Egg Sandwich",
      info: "담백하고 고소한 계란 샐러드에 햄과 치즈를 더한 베이직한 조합의 간편 샌드위치",
      kcal: 490,
      saturatedFat: 8,
      sugar: 12,
      sodium: 820,
      protein: 14,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 돼지고기, 쇠고기",
      gram: 250,
    },
    deli2: {
      best: false,
      type: 201,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del02.png",
      name: "치킨&아보카도 샌드위치",
      en_name: "Chicken & Avocado Sandwich",
      info: "닭가슴살, 아보카도 & 그리너리한 신선한 야채로 구성된 신선하고 아삭한 건강한 샌드위치",
      kcal: 545,
      saturatedFat: 7,
      sugar: 8,
      sodium: 940,
      protein: 35,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 호두, 닭고기",
      gram: 255,
    },
    deli3: {
      best: false,
      type: 202,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del03.png",
      name: "베이컨 에그 베이글",
      en_name: "Bacon Egg Bagel",
      info: "고소하고 쫄깃한 베이글에 잘 구운 베이컨, 에그오믈렛을 더해 따뜻하게 즐기는 모닝 베이글 샌드위치",
      kcal: 540,
      saturatedFat: 8,
      sugar: 12,
      sodium: 1020,
      protein: 20,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 돼지고기",
      gram: 218,
    },
    deli4: {
      best: false,
      type: 203,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del04.png",
      name: "에그마요 소금버터롤",
      en_name: "Egg Mayo Salt Butter Roll",
      info: "고소한 에그마요 필링에 체다치즈로 짭조름함을 더한 소금버터롤 샌드",
      kcal: 380,
      saturatedFat: 10,
      sugar: 7,
      sodium: 530,
      protein: 12,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 쇠고기",
      gram: 123,
    },
    deli5: {
      best: false,
      type: 204,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del05.png",
      name: "클래식 잠봉뵈르",
      en_name: "Classic Jambon Beurre",
      info: "더 바삭하고 촉촉해진 프랑스 바게트에 잠봉햄과 AOP 고메버터를 더한 정통 샌드위치",
      kcal: 565,
      saturatedFat: 19,
      sugar: 2,
      sodium: 950,
      protein: 25,
      caffeine: 0,
      allergy: "우유, 밀, 돼지고기",
      gram: 180,
    },
    deli6: {
      best: true,
      type: 205,
      sub_type: "샐러드",
      url: "images/menuImg/menu-del06.png",
      name: "콥 샐러드",
      en_name: "Cobb Salad",
      info: "신선한 야채와 닭가슴살, 토마토, 계란,치즈, 베이컨에 화이트바베큐드레싱을 곁들여 먹는 샐러드",
      kcal: 330,
      saturatedFat: 7,
      sugar: 4,
      sodium: 760,
      protein: 19,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 토마토, 돼지고기, 닭고기",
      gram: 274,
    },
    deli7: {
      best: false,
      type: 206,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del07.png",
      name: "오리지널 핫도그",
      en_name: "Original Hotdog",
      info: "부드러운 핫도그 빵 속에 육즙 가득한 두꺼운 소시지가 들어간 오리지널 핫도그",
      kcal: 365,
      saturatedFat: 9,
      sugar: 12,
      sodium: 810,
      protein: 14,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 토마토, 돼지고기, 쇠고기",
      gram: 139,
    },
    deli8: {
      best: false,
      type: 207,
      sub_type: "샌드위치",
      url: "images/menuImg/menu-del08.png",
      name: "불고기 반미 샌드위치",
      en_name: "Bulgogi Banh Mi Sandwich",
      info: "바삭한 쌀바게트안에 불고기 양념으로 볶아낸 매콤한 양념을 더한 반미 샌드위치",
      kcal: 385,
      saturatedFat: 4.5,
      sugar: 13,
      sodium: 740,
      protein: 10,
      caffeine: 0,
      allergy: "계란, 우유, 땅콩, 대두, 밀, 쇠고기",
      gram: 178,
    },
    deli9: {
      best: false,
      type: 208,
      sub_type: "샐러드",
      url: "images/menuImg/menu-del09.png",
      name: "머쉬룸 불고기 샐러드",
      en_name: "Mushroom Bulgogi Salad",
      info: "바삭하게 볶아낸 불고기, 새송이, 양파와 담백한 오리엔탈 드레싱에 눈꽃치즈를 더한 부드러운 어울림의 샐러드",
      kcal: 185,
      sugar: 9,
      protein: 10,
      saturatedFat: 4.2,
      sodium: 610,
      caffeine: 0,
      allergy: "우유, 대두, 밀, 토마토, 쇠고기",
      gram: 218
    },
    deli10: {
      best: false,
      type: 209,
      sub_type: "샐러드",
      url: "images/menuImg/menu-del10.png",
      name: "불고기 분짜 누들 샐러드",
      en_name: "Bulgogi Bun Cha Noodle Salad",
      info: "잘 볶아낸 소불고기와 쌀면을 아삭한 무피클과 어우러낸 상큼한 분짜 샐러드",
      kcal: 440,
      sugar: 20,
      protein: 15,
      saturatedFat: 2,
      sodium: 940,
      caffeine: 0,
      allergy: "땅콩, 대두, 밀, 아황산류, 쇠고기",
      gram: 350
    },
    deli11: {
      best: false,
      type: 210,
      sub_type: "간편식",
      url: "images/menuImg/menu-del11.png",
      name: "양송이 크림 스프",
      en_name: "Mushroom Cream Soup",
      info: "향긋한 양송이를 듬뿍 넣어 끓여낸 깊은 풍미의 크림 스프",
      kcal: 240,
      sugar: 7,
      protein: 3,
      saturatedFat: 16,
      sodium: 350,
      caffeine: 0,
      allergy: "우유, 대두, 밀, 닭고기",
      gram: 180
    }
  },
  deserts: {
    desert1: {
      best: true,
      type: 400,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert01.png",
      name: "까망쿠키 속 리얼말차 브라우니",
      en_name: "Real Matcha Brownie inside a Black Cookie",
      info: "까망쿠키가 통째로 올라간 말차반 초코반 브라우니로 달콤 쌉쌀한 맛을 제대로 즐길 수 있는 진한 브라우니 제품",
      kcal: 320,
      saturatedFat: 11,
      sugar: 25,
      sodium: 100,
      protein: 4,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀",
      gram: 73,
    },
    desert2: {
      best: false,
      type: 401,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert02.png",
      name: "초코 콕콕 쿠키",
      en_name: "Choco Chunk Cookie",
      info: "화이트 초콜릿&밀크 초콜릿&다크 청크가 콕콕! 들어간 달콤한 초코 쿠키",
      kcal: 400,
      saturatedFat: 12,
      sugar: 26,
      sodium: 290,
      protein: 5,
      caffeine: 0,
      allergy: "밀, 우유, 대두, 계란, 땅콩",
      gram: 84,
    },
    desert3: {
      best: false,
      type: 402,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert03.png",
      name: "피스타치오 티케이크",
      en_name: "Pistachio Tea Cake",
      info: "고소한 피스타치오를 가득 올려 넛츠 풍미 가득한 디저트",
      kcal: 195,
      saturatedFat: 10,
      sugar: 13,
      sodium: 65,
      protein: 3,
      caffeine: 0,
      allergy: "계란, 우유, 밀",
      gram: 32,
    },
    desert4: {
      best: false,
      type: 403,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert04.png",
      name: "호두파이(조각)",
      en_name: "Walnut Pie (Slice)",
      info: "통밀이 들어가 더욱 고소한 파이속 호두를 가득 채워 더욱 맛있는 조각 호두파이",
      kcal: 310,
      saturatedFat: 2.6,
      sugar: 10,
      sodium: 120,
      protein: 6,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 호두, 아황산류",
      gram: 67,
    },
    desert5: {
      best: false,
      type: 404,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert05.png",
      name: "오리지널 까눌레",
      en_name: "Original Canelé",
      info: "겉은 카라멜화되어 바삭하지만 속은 푸딩같이 부드러운 맛이 일품인 고급 디저트",
      kcal: 100,
      saturatedFat: 1.9,
      sugar: 11,
      sodium: 15,
      protein: 2,
      caffeine: 0,
      allergy: "계란, 우유, 밀",
      gram: 45,
    },
    desert6: {
      best: false,
      type: 405,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert06.png",
      name: "티타임 레몬 슈가 파운드",
      en_name: "Tea Time Lemon Sugar Pound",
      info: "레몬 필이 들어가 레몬의 상큼함을 가득 느낄 수 있는 부드러운 미니 큐브 파운드",
      kcal: 560,
      saturatedFat: 15,
      sugar: 48,
      sodium: 190,
      protein: 6,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 아황산류",
      gram: 135,
    },
    desert7: {
      best: false,
      type: 406,
      sub_type: "마카롱",
      url: "images/menuImg/menu-desert07.png",
      name: "초코가나슈 뚱카롱",
      en_name: "Choco Ganache Macaron",
      info: "진하고 강한 다크 초콜릿이 달콤하게 느껴지는 뚱카롱",
      kcal: 110,
      saturatedFat: 3.3,
      sugar: 9,
      sodium: 15,
      protein: 1,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 쇠고기, 오징어",
      gram: 25,
    },
    desert8: {
      best: false,
      type: 407,
      sub_type: "구움양과",
      url: "images/menuImg/menu-desert08.png",
      name: "베이비슈",
      en_name: "Baby Choux",
      info: "달콤하고 시원한 슈크림이 가득 들어있는 한 입 크기의 맛있는 베이비슈",
      kcal: 95,
      saturatedFat: 4.3,
      sugar: 4,
      sodium: 15,
      protein: 1,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀",
      gram: 30,
    },
    desert9: {
      best: false,
      type: 408,
      sub_type: "마카롱",
      url: "images/menuImg/menu-desert09.png",
      name: "더블치즈 뚱카롱",
      en_name: "Dobule Cheese Dungcaron",
      info: "에멘탈 치즈크림 사이에 고소한 버터 쿠키가 들어있는 마카롱",
      kcal: 110,
      sugar: 8,
      protein: 2,
      saturatedFat: 3.8,
      sodium: 30,
      caffeine: 0,
      allergy: "계란, 우유, 대두, 밀, 쇠고기",
      gram: 25
    },
    desert10: {
      best: false,
      type: 409,
      sub_type: "마카롱",
      url: "images/menuImg/menu-desert10.png",
      name: "딸기우유 뚱카롱",
      en_name: "Strawberry milk Dungcaron",
      info: "풍성한 우유크림에 상큼한 딸기퓨레가 들어가 딸기 우유맛이 입안 가득 퍼지는 뚱카롱",
      kcal: 110,
      sugar: 11,
      protein: 2,
      saturatedFat: 3.6,
      sodium: 35,
      caffeine: 0,
      allergy: "계란, 우유, 밀",
      gram: 28
    },
    desert11: {
      best: false,
      type: 410,
      sub_type: "잼",
      url: "images/menuImg/menu-desert11.png",
      name: "블루베리 크림치즈",
      en_name: "Blueberry Cream Cheese",
      info: "상큼한 블루베리와 부드럽고 고소한 크림치즈가 어우러진 새콤달콤 크림치즈 스프레드",
      kcal: 185,
      sugar: 11,
      protein: 3,
      saturatedFat: 8,
      sodium: 270,
      caffeine: 0,
      allergy: "우유",
      gram: 70
    },
    desert12: {
      best: false,
      type: 411,
      sub_type: "아이스크림",
      url: "images/menuImg/menu-desert12.png",
      name: "초코 아이스캔디 바",
      en_name: "Chocolate Ice Candy Bar",
      info: "초콜릿의 달콤하고 진~한 맛을 시원하게 즐기는 초코 아이스캔디 바",
      kcal: 122,
      sugar: 13,
      protein: 2,
      saturatedFat: 3.7,
      sodium: null,
      caffeine: 0,
      allergy: "우유, 대두",
      gram: 70
    },
    desert13: {
      best: false,
      type: 412,
      sub_type: "초콜릿",
      url: "images/menuImg/menu-desert13.png",
      name: "캐치! 티니핑 팝핑 톡톡 솜사탕",
      en_name: "Catch! Tinyping Popping Cotton Candy",
      info: "입안에 넣으면 달콤하게 녹으면서 팝핑 캔디가 톡톡 터지는 솜사탕",
      kcal: 36,
      sugar: 9,
      protein: 0,
      saturatedFat: 0,
      sodium: 0,
      caffeine: 0,
      allergy: "대두, 우유",
      gram: 9
    },
  },
  drinks: {
    drink1: {
      best: false,
      type: 300,
      sub_type: "빙수",
      url: "images/menuImg/menu-drink01.png",
      name: "와르르 베리베리 빙수",
      en_name: "Berry Berry Bingsu",
      info: "네가지 타입의 믹스베리 토핑물을 우유 얼음 위에 가득 올려 와르르 쏟아질 것만 같은 풍성함이 느껴지는 빙수",
      kcal: 565,
      saturatedFat: 8,
      sugar: 95,
      sodium: 190,
      protein: 9,
      caffeine: 0,
      allergy: "우유",
      gram: 690,
    },
    drink2: {
      best: false,
      type: 301,
      sub_type: "티",
      url: "images/menuImg/menu-drink02.png",
      name: "납작 복숭아 아이스티(제로)",
      en_name: "Flat Peach Iced Tea (Zero)",
      info: "납작 복숭아 품종을 활용해 달콤한 과일의 풍미를 올린 제로 칼로리 아이스티",
      kcal: 0,
      saturatedFat: 0,
      sugar: 0,
      sodium: 5,
      protein: 0,
      caffeine: 0,
      allergy: "복숭아",
      gram: 400,
    },
    drink3: {
      best: false,
      type: 302,
      sub_type: "빙수",
      url: "images/menuImg/menu-drink03.png",
      name: "팥절미 컵빙수",
      en_name: "Red Bean Rice Cake Cup Bingsu",
      info: "혼자서도 부담없이 시원하게 즐길 수 있는 컵빙수",
      kcal: 345,
      saturatedFat: 3.8,
      sugar: 1,
      sodium: 50,
      protein: 11,
      caffeine: 0,
      allergy: "우유, 대두",
      gram: 100,
    },
    drink4: {
      best: true,
      type: 303,
      sub_type: "커피",
      url: "images/menuImg/menu-drink04.png",
      name: "아메리카노",
      en_name: "Americano",
      info: "뚜레쥬르만의 스페셜 고급원두를 적절한 비율로 블렌드 하여 커피 본연의 맛과 향을 살린 따뜻한 아메리카노 음료",
      kcal: 15,
      saturatedFat: 0,
      sugar: 0,
      sodium: 0,
      protein: 1,
      caffeine: 166,
      allergy: "",
      gram: 310,
    },
    drink5: {
      best: false,
      type: 304,
      sub_type: "커피",
      url: "images/menuImg/menu-drink05.png",
      name: "아이스 아메리카노",
      en_name: "Iced Americano",
      info: "뚜레쥬르만의 스페셜 고급원두를 적절한 비율로 블렌드 하여 커피 본연의 맛과 향을 살린 시원한 아메리카노",
      kcal: 15,
      saturatedFat: 0,
      sugar: 0,
      sodium: 0,
      protein: "1g미만",
      caffeine: 166,
      allergy: "",
      gram: 350,
    },
    drink6: {
      best: false,
      type: 305,
      sub_type: "커피",
      url: "images/menuImg/menu-drink06.png",
      name: "카페라떼",
      en_name: "Cafe Latte",
      info: "뚜레쥬르만의 스페셜 고급원두로 추출한 풍부한 풍미의 에스프레소와 스팀우유가 어우러진 따뜻한 라떼 음료",
      kcal: 180,
      saturatedFat: 7,
      sugar: 13,
      sodium: 130,
      protein: "1g미만",
      caffeine: 166,
      allergy: "우유",
      gram: 320,
    },
    drink7: {
      best: false,
      type: 306,
      sub_type: "커피",
      url: "images/menuImg/menu-drink07.png",
      name: "아이스 바닐라라떼",
      en_name: "Iced Vanilla Latte",
      info: "뚜레쥬르만의 스페셜 고급원두로 추출한 풍부한 풍미의 에스프레소와 우유, 그리고 향긋한 바닐라 시럽이 어우러진 시원하고 달달한 음료",
      kcal: 160,
      saturatedFat: 3,
      sugar: 25,
      sodium: 55,
      protein: 4,
      caffeine: 166,
      allergy: "우유",
      gram: 350,
    },
    drink8: {
      best: true,
      type: 307,
      sub_type: "커피",
      url: "images/menuImg/menu-drink08.png",
      name: "원샷! 아샷추",
      en_name: "One Shot! Peach Tea Espresso",
      info: "달콤한 복숭아 홍차에 에스프레소 샷을 더해 더운 날씨에도 깔끔하게 즐길 수 있는 에스프레소 음료",
      kcal: 190,
      saturatedFat: 0,
      sugar: 36,
      sodium: 0,
      protein: 1,
      caffeine: 166,
      allergy: "복숭아",
      gram: 580,
    },
    drink9: {
      best: false,
      type: 308,
      sub_type: "우유",
      url: "images/menuImg/menu-drink09.png",
      name: "곰돌이 푸 신선한 우유",
      en_name: "Winnie the Pooh Fresh Milk",
      info: "원유의 영양과 신선함을 그대로 담고 있는 고소한 흰 우유",
      kcal: 125,
      sugar: 11,
      protein: 5,
      saturatedFat: 5,
      sodium: 130,
      caffeine: 0,
      allergy: "우유 함유",
      gram: 200
    },
    drink10: {
      best: false,
      type: 309,
      sub_type: "과일주스",
      url: "images/menuImg/menu-drink10.png",
      name: "자몽 에이드",
      en_name: "Grapefruit Ade",
      info: "자몽과육과 탄산수를 넣어 톡 쏘는 맛이 일품인 자몽에이드",
      kcal: 95,
      sugar: 22,
      protein: 0,
      saturatedFat: null,
      sodium: null,
      caffeine: 0,
      allergy: null,
      gram: 390
    },
  }
}


// 뚜레쥬르 매장 정보
stores = {
  서울: [
    {
      name: "제일제당센터점",
      location: "서울 중구 동호로 330 CJ제일제당빌딩 1층",
      call: "02-6740-7930",
    },
    {
      name: "카페역삼점",
      location: "서울 강남구 테헤란로8길 21 강남화인빌딩 1층",
      call: "070-4007-8150",
    },
    {
      name: "공덕해링턴점",
      location: "서울 마포구 마포대로 92 효성해링턴스퀘어 B동 1층 1호",
      call: "02-2197-0207",
    },
    {
      name: "강남직영점",
      location: "서울 강남구 강남대로 438 스타플렉스 1층",
      call: "02-565-4048",
    },
    {
      name: "뱅뱅사거리점",
      location: "서울 강남구 도곡로 112 서한빌딩 1층 101호",
      call: "02-577-9585",
    },
    {
      name: "강남구청역점",
      location: "서울 강남구 선릉로 664 건설빌딩 1층 101호",
      call: "02-514-8777",
    },
    {
      name: "카페강남대로점",
      location: "서울 강남구 강남대로 524 건일빌딩 1층 102~104호",
      call: "02-545-3644",
    },
    {
      name: "잠실점",
      location: "서울 송파구 석촌호수로 142 빈즈빌딩 1층",
      call: "02-423-9470",
    },
    {
      name: "공덕역점",
      location: "서울 마포구 백범로 178 마포신영지웰 1층 1호",
      call: "02-2123-9999",
    },
    {
      name: "신당역점",
      location: "서울 중구 퇴계로 404 1층",
      call: "02-2252-2876",
    },
  ],
  대전: [
    {
      name: "대전월평계룡점",
      location: "대전 서구 월평로 46 1층",
      call: "042-485-0915",
    },
    {
      name: "대전오류중앙점",
      location: "대전 중구 계룡로 846 삼정빌딩 1층",
      call: "042-522-0489",
    },
    {
      name: "대전월평선사점",
      location: "대전 서구 청사로 128 1층",
      call: "042-485-0322",
    },
    {
      name: "대전중촌점",
      location: "대전 중구 목중로 24 1층",
      call: "042-221-7979",
    },
    {
      name: "대전탄방역점",
      location: "대전 서구 문정로 64 송림빌딩 1층 101호",
      call: "042-483-0606",
    },
    {
      name: "대전장대점",
      location: "대전 유성구 문화원로 2 1층",
      call: "042-823-7997",
    },
    {
      name: "대전대동오거리점",
      location: "대전 동구 동대전로 80-2 1층",
      call: "042-633-0454",
    },
    {
      name: "대전도안봉명점",
      location: "대전 유성구 계룡로132번길 10 도안센트럴프라자 1층",
      call: "070-7543-6504",
    },
    {
      name: "대전관저점",
      location: "대전 서구 구봉로 137 밀리온빌딩 1차 1층 106호",
      call: "042-542-5620",
    },
    {
      name: "대전법동점",
      location: "대전 대덕구 동춘당로 167 1층",
      call: "042-627-0455",
    },
    {
      name: "대전둔산법원점",
      location: "대전 서구 둔산로137번길 44 서림빌딩 1층 103호",
      call: "042-482-0933",
    },
    {
      name: "대전태평점",
      location: "대전 중구 평촌로 111 상가 104~105호",
      call: "042-535-6379",
    },
    {
      name: "대전둔산샘머리점",
      location: "대전 서구 청사로 281 샘머리코아 1층 110호",
      call: "042-489-6879",
    },
    {
      name: "대전신탄진대청점",
      location: "대전 대덕구 대청로 38 1층",
      call: "042-721-9081",
    }
  ],
  대구: [
    {
      name: "대구달성공원역점",
      location: "대구 중구 달성로 123 달성파크푸르지오힐스테이트 상가 1층 102호",
      call: "053-571-0101",
    },
    {
      name: "대구역오페라점",
      location: "대구 북구 칠성남로 70 근린생활시설동 1층 127~129호",
      call: "053-341-9903",
    },
    {
      name: "동대구더샵디어엘로점",
      location: "대구 동구 화랑로 33 상가동 301동 1층 107~108호",
      call: "053-751-9997",
    },
    {
      name: "대구남산점",
      location: "대구 중구 남산로7길 7 남산역화성파크드림 302동 1층",
      call: "053-252-1978",
    },
    {
      name: "복현GS점",
      location: "대구 북구 검단로 12 1층",
      call: "없음",
    }
  ],
  청주: [
    {
      name: "청주율량점",
      location: "충북 청주시 청원구 율봉로 178 1층",
      call: "043-212-8204",
    },
    {
      name: "청주용암부영점",
      location: "충북 청주시 상당구 중흥로 199 1층",
      call: "043-283-0356",
    },
    {
      name: "청주산남계룡점",
      location: "충북 청주시 서원구 산남로 22 산남렉슬2 1층 105~106호",
      call: "043-296-0455",
    },
    {
      name: "오송파라곤점",
      location: "충북 청주시 흥덕구 오송읍 오송생명7로 164 1층",
      call: "043-232-7942",
    },
    {
      name: "청원내수점",
      location: "충북 청주시 청원구 내수읍 청암로 54 1-2층",
      call: "없음",
    },
  ],
  인천: [
    {
      name: "인천시청점",
      location: "인천 남동구 구월로 81 1층",
      call: "032-425-6767",
    },
    {
      name: "주안파크자이점",
      location: "인천 미추홀구 인하로221번길 6 다안빌딩 1층 103호",
      call: "032-865-8800",
    },
    {
      name: "산곡푸르지오점",
      location: "인천 부평구 마장로324번길 82 1층",
      call: "032-330-2115",
    },
    {
      name: "카페석남점",
      location: "인천 서구 가정로 246 1층 105호",
      call: "032-575-0876",
    },
    {
      name: "신기점",
      location: "인천 미추홀구 미추홀대로 589 나동 108호",
      call: "032-868-2124",
    },
  ],
  부산: [
    {
      name: "부산중앙대로점",
      location: "부산 중구 중앙대로 145 내일투어 1층",
      call: "051-462-3632",
    },
    {
      name: "부산시청점",
      location: "부산 부산진구 진연로 5 1-2층",
      call: "051-866-2624",
    },
    {
      name: "부산서면점",
      location: "부산 부산진구 신천대로50번길 61 1층",
      call: "051-802-6190",
    },
    {
      name: "부산사상터미널점",
      location: "부산 사상구 사상로 204 1층",
      call: "051-916-8000",
    },
    {
      name: "사랑모아범천점",
      location: "부산 부산진구 중앙대로 632 사랑모아빌딩 1층",
      call: "없음",
    },
  ],
  울산: [
    {
      name: "울산삼산점",
      location: "울산 남구 삼산중로48번길 13 1층",
      call: "052-222-6177",
    },
    {
      name: "울산무거점",
      location: "울산 남구 대학로147번길 61 1층",
      call: "052-223-6336",
    },
    {
      name: "울산신정현대점",
      location: "울산 남구 대암로 50 1층",
      call: "052-258-8383",
    },
    {
      name: "울산매곡점",
      location: "울산 북구 신기3길 40 1층",
      call: "052-975-7843",
    },
    {
      name: "울산달동본점",
      location: "울산 남구 번영로107번길 6 1층",
      call: "없음",
    },
  ]
}